### ISSUE TITLE
[DOC] Docker for a backend and frontend apps

### ISSUE THREAD

**Issue by mdanilowicz** [shopware/frontends#1038]
### Description

Prepare an example of preparing docker and docker networks to communicate frontend and backend. 
https://shopwarecommunity.slack.com/archives/C050L6NCMGQ/p1718796847256709

### Use Case

Community question

**Comment by BrocksiNet** [comment]
I was working on this the last few days and would need some peps for testing. :grinning: 

Have a look at [docker-composable-frontends](https://github.com/shopwareLabs/docker-composable-frontends). Feedback is welcome. Thx.
