### ISSUE TITLE
[BUG] 500 for no product found for navigation Id issue 

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Go to the https://frontends-demo.vercel.app/Beach-bag-NYK/SW10411 , we get` Error: No product found for navigationId: 0c0995b393d74e91bdf00ffdf9bfb2a0  `  and after reloading the page 
<img width="1508" alt="Screenshot 2024-07-04 at 13 41 24" src="https://github.com/shopware/frontends/assets/30267600/986ccd25-5688-4f00-9d47-c150db8a2502">

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by mkucmus** [comment]
the API issue is reported under internal task `NEXT-37152`
