### ISSUE TITLE
[BUG] Stackblitz templates console errors 

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#1116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, our tests for stackblitz templates fail due to errors in the console : 

-  Vue demo store 
`VM9 vue-demo-store:2 Uncaught (in promise) Error: Could not find source file: 'stackblitz:/.eslintrc.js'.`
`Uncaught (in promise) Error: Could not find source file: 'stackblitz:/.nuxt/app.config.mjs'`
- Astro
`Uncaught (in promise) Error: Could not find source file: 'stackblitz:/astro.config.mjs'.`
- Vue blank
`Uncaught (in promise) Error: Could not find source file: 'stackblitz:/.nuxt/dist/server/server.mjs'.`

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by basarat** [comment]
I'm experiencing this as well.
