### ISSUE TITLE
[BUG] Criteria type mismatch between adminApiTypes and storeApiTypes

### ISSUE THREAD

**Issue by smnhgn** [shopware/frontends#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The type for Criteria in adminApiTypes doesn't seem up-to-date (compared to storeApiTypes).
Here a picture of the diff (adminApiTypes <-> storeApiTypes):

![Bildschirmfoto 2024-07-17 um 11 12 28](https://github.com/user-attachments/assets/a7b725c7-ebd3-4ac1-a358-329a17b56d80)

Currently i'm having 2 main issues with the types in adminApiTypes:

- `associations?: Record<string, never>;` always shows a ts error (workaround -> `as any`)
- `includes` is missing (workaround -> `// @ts-ignore`)

### Expected Behavior

Criteria types in adminApiTypes should work as expected.

### Environment

```markdown
- @shopware/api-client: 1.0.1
```

**Comment by mkucmus** [comment]
the missing parts of Criteria type is now available under `canary` version of `api-client` package. let me know if it works for you.
