### ISSUE TITLE
Missing sw-context-token while login 

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#112]
A case that occurs during e2e tests for login scenarios
![image](https://user-images.githubusercontent.com/30267600/230306700-f186fb3a-2f65-4053-9603-464aabccb159.png)

trace from failed test 
[0fd11437b8c875ad3e11790d597a2aba179f838c.zip](https://github.com/shopware/frontends/files/11167515/0fd11437b8c875ad3e11790d597a2aba179f838c.zip)

can be viewed here: https://trace.playwright.dev/

**Comment by mkucmus** [comment]
related issue in the core: NEXT-24824

**Comment by patzick** [comment]
@mkucmus maybe we should invoke a refresh session on the login form so the session is created?

**Comment by mkucmus** [comment]
yes, that can fix it temporarily. I found that any other endpoint (other than /login) will do the trick because it's not buggy in this way and will respond with context token so api-client will have it in the every next request

**Comment by patzick** [comment]
@mkucmus, so let's invoke it once more just before `login` request and leave TODO comment with link to this issue, we'll not close it, but it will unblock #75

**Comment by mkucmus** [comment]
> @mkucmus, so let's invoke it once more just before `login` request and leave TODO comment with link to this issue, we'll not close it, but it will unblock #75

fixed via #138 if it's ok to have it only on presentation layer, I left a link also in `login` js-doc within composable.

**Comment by mkucmus** [comment]
let's leave it here because there is no issue to track on GH.

I've got internal reference: `NEXT-24824`

**Comment by mkucmus** [comment]
should be tested with version v6.5.1 where the fix will be available.

**Comment by BrocksiNet** [comment]
I guess we can test and close this maybe.
Moving back the issue into ToDo.

**Comment by mkucmus** [comment]
there is no problem on the latest version of Shopware 6, so I'm closing the issue.

**Comment by jonathan-martz** [comment]
// TODO: remove this line once the https://github.com/shopware/frontends/issues/112 issue is fixed

I found this Todo in the Code of the Demo Store Template, so looks like you could remove into from the Template or ?

**Comment by PheysX** [comment]
Push :D
