### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, it is not possible to proceed to checkout and go to my account 
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')`

https://github.com/user-attachments/assets/23678456-9040-4ea0-aebc-6a32fd586709

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by patzick** [comment]
closed by #1177
