### ISSUE TITLE
[BUG] Could not resolve "#imports" in `product-detail-page` example (stackblitz only)

### ISSUE THREAD

**Issue by mkucmus** [shopware/frontends#1213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

project does not run, for example https://stackblitz.com/github/shopware/frontends/tree/main/examples/product-detail-page?file=vite.config.js

### Expected Behavior

I'm able to run the project

### Steps To Reproduce

1. go to https://stackblitz.com/github/shopware/frontends/tree/main/examples/product-detail-page?file=vite.config.js
2. watch the console to see the errors

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by 1amGr00t** [comment]
@mkucmus I tried to create a custom Vue application with shopware frontends, but I run into the same errors as the "#imports" imports could not be resolved in different files from "@shopware-pwa/composable-next". Will there be a bug release soon?
