### ISSUE TITLE
[BUG]  Open empty mini cart on thankyou page 

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#1307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Screen Recording 2024-09-23 at 16.58.58

### Expected Behavior

the open minicart will not be displayed

### Steps To Reproduce

add anything to your cart and place your order

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by khanSoliheen** [comment]
@kstala , I am not able to view the video. Can you provide the more details on this issue? After placing an order I am able to see this screen 
<img width="1440" alt="Screenshot 2024-09-26 at 20 49 23" src="https://github.com/user-attachments/assets/853fb789-905a-464b-b292-96c0479b25b6">
