### ISSUE TITLE
[BUG] Order lines hide/view options do not work 

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#1309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The hide/view options for hiding or displaying order lines do not work on the order confirmation 

https://github.com/user-attachments/assets/1e4158e9-c235-4c73-9950-8c78754fe16b

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by khanSoliheen** [comment]
You can find the PR [here](https://github.com/shopware/frontends/pull/1317)

**Comment by mkucmus** [comment]
completed via #1317
