### ISSUE TITLE
[BUG] Missing CMS component

### ISSUE THREAD

**Issue by mdanilowicz** [shopware/frontends#1373]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Missing CMS components for https://frontends-demo.vercel.app/CMS/CMS-test/

```
CmsBlockImageGalleryBig
CmsBlockSpatialViewer
```

### Environment

- OS:
- Node:
- pnpm:

**Comment by BrocksiNet** [comment]
This issue is a duplicate of 🔽 

CmsBlockSpatialViewer ➡ https://github.com/shopware/frontends/issues/1305
CmsBlockImageGalleryBig ➡ https://github.com/shopware/frontends/issues/1306
