### ISSUE TITLE
[BUG] Category breadcrumbs path is missing

### ISSUE THREAD

**Issue by StanislovasRamanauskas** [shopware/frontends#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently useBreadcrumbs() composable only returns names array for category breadcrumbs. Paths are missing so link to category cannot be created.

E.G.
```js
{
  "name": "Food"
}
```

Helper function to get breadcrumbs getCategoryBreadcrumbs() also gather only names:
```js
export function getCategoryBreadcrumbs(
  category: Category | null | undefined,
  options?: {
    /**
     * Start at specific index if your navigation
     * contains root names which should not be visible.
     */
    startIndex?: number;
  }
) {
  const breadcrumbs =
    category?.translated?.breadcrumb || category?.breadcrumb || [];
  const startIndex = options?.startIndex || 0;
  if (breadcrumbs.length <= startIndex) return [];
  return breadcrumbs.slice(startIndex).map((element) => {
    return {
      name: element,
    };
  });
}
```

Breadcrumbs in product.seoCategory / category API response also contain only names. So I think this is issue both in BE and FE parts:
![Screenshot from 2023-04-14 00-07-12](https://user-images.githubusercontent.com/38095299/231883067-4f2a619d-81c8-4099-b3da-b3bd7e05c490.png)

### Expected Behavior

As declared in useBreadcrumbs return type I expect category breadcrumb with path returned:
```
type Breadcrumb = {
    name: string;
    path?: string;
};
```

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by BrocksiNet** [comment]
Thx for submitting this already known issue. We have an discussion already with the product area that is responsible to return the path via API. Also good to have this issue here to do not forget it. Will ping you when I have news about this.

**Comment by BrocksiNet** [comment]
@patzick could we use the same technic we used for "duplicated" seoURL''s calls to solve this issue? Like looking in the list if we have this seoURL already and then adding the link instead of waiting for the changed response? Just an idea.

**Comment by BrocksiNet** [comment]
@StanislovasRamanauskas here is an example of how to solve this in frontends (but this is just a workaround):
https://github.com/shopware/frontends/pull/258/files

And I do not know if we will merge this into the demo-store.

**Comment by BrocksiNet** [comment]
For reference: NEXT-24954

**Comment by BrocksiNet** [comment]
I am preparing the MR to get the new Endpoints into the Core of Shopware. After that, we can update the composables and have a proper solution. :raised_hands: But I need to find out which version it will be released.

**Comment by BrocksiNet** [comment]
The [changes](https://github.com/shopware/shopware/blob/b85b5e808d23aa4271d0a583cfcff87a907708c2/src/Core/Framework/Api/ApiDefinition/Generator/Schema/StoreApi/paths/breadcrumb.json#L2) are already in the trunk so we can start with the frontend part. This is not blocked anymore.

**Comment by SuddenDev** [comment]
@BrocksiNet Do you have any news when this feature will be rolled out on Shopware Core? Since I've built a shop with 0.X versions of the frontend, I'll probably not refactor everything, but the API should still be accessible with fetch or similar tools if everything else fails.
