### ISSUE TITLE
[FEATURE] Make Threejs optional

### ISSUE THREAD

**Issue by jo-nas** [shopware/frontends#1519]
### Description

Problem:
Currently, the Shopware frontend framework loads the three.js JavaScript library for all shops, regardless of whether the shop needs it or not. This results in unnecessary overhead for stores that do not use any 3D rendering features, as the library is loaded globally for every shop instance.

### Use Case

The three.js library should be optional and only loaded when it's actually needed, i.e., when the shop uses 3D visualizations or any other features that require the library. This would help reduce the overall size of the frontend assets and improve performance for shops that do not need the library.

**Comment by jo-nas** [comment]
OK if seen that it only loads as a asyncComponent. Only the nuxt bundle size analyzer tool shows it in the total bundle size.

**Comment by BrocksiNet** [comment]
@jo-nas, do you mean because it is bundled? Where do you see it? 
Because I remember we included it as a [lazy component](https://nuxt.com/docs/guide/directory-structure/components#dynamic-imports).

**Comment by jo-nas** [comment]
I have used nuxt analyze to analyze the bundle size of the frontend. And was confused by the importing of threejs.
![Image](https://github.com/user-attachments/assets/296c0611-3fea-49b2-b02a-d2cb8004bc81)


I think we can close it because it loads as a lazy component. It is only a problem for analyzing the bundle size not the real data for the enduser. The enduser will never load the component if no 3D object is used as a image. So you did a great job. I missed up on looking into the implementation.
