### ISSUE TITLE
[BUG] Wrong typing of CountryState

### ISSUE THREAD

**Issue by LouisEiermann** [shopware/frontends#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The typing of `CountryState` seems not to match the values that we get out of the API. This is the typing from CountryState.d.ts:

```
export type CountryState = {
  countryId: string;
  shortCode: string;
  name: string | null;
  position: number;
  active: boolean;
  country: Country | null;
  translations: CountryStateTranslation[] | null;
  customerAddresses: CustomerAddress[] | null;
  orderAddresses: OrderAddress[] | null;
  customFields: CustomField[];
};
```

As you can see, the value `id` is missing, and `translated` also is not there, instead there is a value called `translations`.

You can see the response from the API in this screenshot that depicts the value for a state:

![Bildschirmfoto 2023-04-21 um 12 00 43](https://user-images.githubusercontent.com/64272749/233615001-9d2cdf0c-9758-4f49-98c0-453a8fa48597.png)
 
Here you can see a Typescript error that is produced by the mismatch:

![Bildschirmfoto 2023-04-21 um 12 00 19](https://user-images.githubusercontent.com/64272749/233614969-122171a2-5fa9-4c7b-942e-4729f6c7245f.png)

### Expected Behavior

The Typing is correct

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by LouisEiermann** [comment]
Additionally, in CustomerAddress.d.ts, countryState is of the type `string`, but that needs to be of the type `CountryState` as well.

```
export type CustomerAddress = {
  customerId?: string;
  countryId: string;
  countryStateId?: string | null;
  salutationId: string;
  firstName: string;
  lastName: string;
  zipcode: string;
  city: string;
  company?: string | null;
  department?: string | null;
  title?: string | null;
  street: string;
  vatId?: string | null;
  phoneNumber?: string | null;
  additionalAddressLine1?: string;
  additionalAddressLine2?: string;
  country?: Country;
  countryState?: string;
  salutation?: Salutation | null;
  customer?: string;
  customFields?: CustomField;
  id: string;
};
```

**Comment by BrocksiNet** [comment]
I guess this will be fixed with new API Client but we should also fix this in old one.
Thx for providing this issue. We will work on this.
