### ISSUE TITLE
[BUG] Hydration on shared price

### ISSUE THREAD

**Issue by patzick** [shopware/frontends#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/13100280/233941555-95de87aa-22ba-4b58-b3a4-8ded18b79766.png)

### Expected Behavior

no hydration error on shared price component

### Steps To Reproduce

1. Go to product listing in development mode
2. Refresh page

### Environment

```markdown
not related
```

**Comment by mdanilowicz** [comment]
```[nuxt] [request error] [unhandled] [500] Context conflict```

Probably related to this error  ☝️
