### ISSUE TITLE
Syntax Error in CmsElementText.vue

### ISSUE THREAD

**Issue by benjamin-ott** [shopware/frontends#20]
The CmsElementText.vue component produces the following error:

Uncaught (in promise) SyntaxError: The requested module '/_nuxt/node_modules/he/he.js?v=536aebf1' does not provide an export named 'default' (at CmsElementText.vue:8:1)

![Bildschirmfoto 2022-11-04 um 09 37 52](https://user-images.githubusercontent.com/8365682/199929218-cf97e57b-1215-4bab-9399-2baa9190901c.png)

**Comment by benjamin-ott** [comment]
Adding this to the tsconfig.json file seems to solve the problem:
`"compilerOptions": {
        "esModuleInterop": true
    }`

**Comment by elkmod** [comment]
Hi @benjamin-ott, we're looking at this issue right now. he.js is a dependency which is required to parse the string value of a text element into a DOM-tree, so we can replace all `<a>` tags with the native `<nuxt-link>` link elements. We are looking into cheaper replacements at the moment.

**Comment by patzick** [comment]
thanks @benjamin-ott , that should be now fixed with `0.2.0`
https://github.com/shopware/frontends/blob/main/packages/cms-base/CHANGELOG.md#020

please let us know if there is still a problem, then we'll reopen the issue 🖖
