### ISSUE TITLE
[FEATURE] Improve Messages and document how to use

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#213]
### Description

**Quote from Tanja Bayer** ([see](https://shopwarecommunity.slack.com/archives/C02TZE6UCJZ/p1683727070157629))
> Another mistery I am trying to solve. How can cart error messages be cleared? If I a user adds a voucher code which he is not allowed to used (e.g. wrong shipping country) the cart gets an error:
> “promotion-not-eligible”
> Is there a way to acknowledge this error, because no matter what I do the error will  stay in the cart…
> I assume the only way is to keep an own error state and show only new errors… as also suggested in a TODO comment in shopware frontends https://github.com/shopware/frontends/blob/3764736e52fffb7f7abeb4c044dee2adc812cbb6/packages/composables/src/useCart.ts#L147 :smile: 
> And why is the cart adding success messages to the errors object?
> promotion-discount-added-7a26337b71e449cc860347af8b6b2931

**Quote from Stepan Lukachyna**
> In fact for me not clear how to handle cart error messages cuz it contains also information messages not only errors.

### Use Case

Important for Developers to know how to work with Messages that are coming back from the API.

### Proposed Solution

- Test how Messages are working and maybe think about modern "Toast Messages".
- We should solve the ToDo that is in the code.
- We should document how to handle messages (error, info and success).

**Comment by mdanilowicz** [comment]
https://github.com/shopware/frontends/pull/249
