### ISSUE TITLE
Add default storefrontUrl to the runtime config

### ISSUE THREAD

**Issue by mkucmus** [shopware/frontends#227]
The issue covers two topics:
- to provide default storefrontUrl for demo purposes (stackblitz missing) by adding .stackblitzrc, for instance.
-  ~~change the structure of shopware-related runtime config~~ (wasn't necessary)

`vue-demo-store` template needs to have storefrontUrl defined in order to registration and other endpoionts storefrontUrl-related work as expected (no HTTP 400).

- we can do it only for stackblitz, adding `.stackblitzrc` or extending a package.json file containing corresponding env which replaces  storefrontUrl runtime config
- ~~globally by adding a default value to the .env or extending `nuxt.config.ts`~~ (was already done)

~~regardless the way we choose, we need to reorganize a structure for runtime config `shopware` namespace. To easy replace those values by environment variables, they need to be flattened and be available in the `public` config root~~

~~instead of nested structure which cannot be replaced by providing corresponding env variables. Thanks to this, we could use `env` config for `.stackblitzrc` or every environment has a possibility to easily override the config~~

RESOURCES:
- https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables
- https://developer.stackblitz.com/platform/webcontainers/project-config#with-project-files

**Comment by BrocksiNet** [comment]
How is that different from `devStorefrontUrl`?
https://github.com/shopware/frontends/blob/main/templates/vue-demo-store/nuxt.config.ts#L10

**Comment by mkucmus** [comment]
currently It can't be replaced by env variable in a nuxt way (see https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables). Under the hood, it will behave exactly the same (with some adjustments in the plugin).
