### ISSUE TITLE
Middleware doesn't work with useUser composable

### ISSUE THREAD

**Issue by benjamin-ott** [shopware/frontends#26]
Hi,

i created a nuxt middleware to restrict access to certain pages.  
Therefore i imported the useUser composable and tried to check the isLoggedIn status.
But i got the following error:
![middleware not working](https://user-images.githubusercontent.com/8365682/202401235-1455eb57-7e50-4131-ab03-ef3a2aae580e.png)
-> "Shopware context is not available"

Did i do something wrong or is this not supported yet?
Thank you in advance for checking.

**Comment by patzick** [comment]
hey @benjamin-ott !
Could you provide a small reproduction of that middleware using our Nuxt template?
https://stackblitz.com/github/shopware/frontends/tree/main/templates/vue-blank
or
https://stackblitz.com/github/shopware/frontends/tree/main/templates/vue-demo-store

**Comment by benjamin-ott** [comment]
@patzick no problem.
Please just copy the 2 following files in an existing vue-demo-store setup: 
[vue-demo-store-middleware-test.zip](https://github.com/shopware/frontends/files/10056611/vue-demo-store-middleware-test.zip)

**Comment by patzick** [comment]
hey @benjamin-ott 
sorry it took so long, needed to discover some possibilities.

Overall Nuxt guards are something unusual and they are fired outside Vue instance, so they do not have access to application data in a "standard Vue's way". 
Trying a way with middleware was causing more and more troubles it requires either do something like
```ts
  nuxtApp.hook("vue:setup", () => {
    const sessionContextData = useState("swSessionContext");
    //...
```
which not always work! Or so dome additional data fetching with API client, but then hard to pass it back to Vue's instance.

Also with Nuxt middlewares you need to register them in every page component, so for example you cannot register it on `AccountLayout` and be done with auth.

### Proposed solution 
For that I prepared a separate composable inside the template. So this way you can do

```vue
<script setup lang="ts">
useAuthGuardRedirection();
</script>
```
inside any page or layout component. It will not only block access to page on SSR/CRS, but also will throw you out in case your login state changes being on that page. Logic of the composable can be adjusted to your needs, it's only a suggested way of handling this. But if you'll have some better ideas let us know :)

composable is here: https://github.com/shopware/frontends/blob/main/templates/vue-demo-store/composables/useAuthGuard.ts
and usage examples:
- https://github.com/shopware/frontends/blob/main/templates/vue-demo-store/layouts/account.vue#L8
- https://github.com/shopware/frontends/blob/main/templates/vue-demo-store/pages/checkout/success/%5Bid%5D.vue#L2


Is that helpful enough for you?

**Comment by benjamin-ott** [comment]
hi @patzick,

thank you very much, this looks promising and should solve our use case (limit certain pages to logged in users)
I will try this as soon as possible.

But i need to update the @shopware-pwa/composables-next package right? As of now it seems there is no new version available.

Thanks again.

**Comment by patzick** [comment]
@benjamin-ott it's released now :)

**Comment by benjamin-ott** [comment]
@patzick Thank you for helping out! It works really well and solves our use case.
