### ISSUE TITLE
[BUG] Clear wishlist for logged in users

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As a logged in user, the clear wishlist option doesn't work

https://github.com/shopware/frontends/assets/30267600/83ca77a9-17ab-4c45-8db7-fef6c9d46356

`{"errors":[{"code":"0","status":"405","title":"Method Not Allowed","detail":"No route found for \u0022GET https:\/\/demo-frontends.shopware.store\/store-api\/customer\/wishlist\/delete\/2623b5f974f3438a850254c86b758478\u0022: Method Not Allowed (Allow: DELETE)"}]}`

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by BrocksiNet** [comment]
There is much more broken. I can not reproduce this exact error, but I can produce other errors that are mostly only there when you are logged in.

**Comment by patzick** [comment]
Reopening as PR was reverted
