### ISSUE TITLE
[BUG] add to cart notification message

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The problem affects products added from the search results level 
<img width="1482" alt="image" src="https://github.com/shopware/frontends/assets/30267600/2b41d3fc-e9e9-438d-8151-bb96774f6b89">

and products with variants 
<img width="1313" alt="image" src="https://github.com/shopware/frontends/assets/30267600/e3745dae-c7ff-4446-bb78-3a05bf39b569">

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by mdanilowicz** [comment]
https://github.com/nuxt-modules/i18n/issues/1569

**Comment by mdanilowicz** [comment]
Blocked by https://github.com/nuxt-modules/i18n/issues/2215
