### ISSUE TITLE
User addresses on account/address page are not showing in demo store

### ISSUE THREAD

**Issue by benjamin-ott** [shopware/frontends#27]
This problem occurs only if you copy the link and paste it in the browser bar (shopXy.com/account/address).
The addresses are showing if you navigate there via the header e.g., but if you reload the page they are gone.

I think this could be related to the useAsyncData function call in the page. I noticed if i move this logic part to the layout it works.

**Comment by mdanilowicz** [comment]
Thank you @benjamin-ott 

The bug has been fixed
