### ISSUE TITLE
[BUG]  CmsElementText component does not work with CMS text styles

### ISSUE THREAD

**Issue by StanislovasRamanauskas** [shopware/frontends#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CmsElementText component from cms-base package does not work with CMS builder text block styles (text color/size, tables, ordered/unordered lists, etc):

In CMS builder:
![Screenshot from 2023-06-20 11-05-58](https://github.com/shopware/frontends/assets/38095299/cbdc35c8-5fd9-4f38-ae13-7a0c22dbe166)

In Frontends:
![Screenshot from 2023-06-20 11-07-44](https://github.com/shopware/frontends/assets/38095299/59f6ea75-7f97-44bb-90ba-4e4403e62561)

### Expected Behavior

CMS Text block styles should be rendered in Frontends so that shop owners could modify text styles from admin side.

### Steps To Reproduce

1. Create Text block in Shopping Experiances page in Shopware admin
2. Add styles to Text block
3. Check page in Frontends.

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by BrocksiNet** [comment]
@StanislovasRamanauskas are the styles still available in the store API response?

**Comment by StanislovasRamanauskas** [comment]
> @StanislovasRamanauskas are the styles still available in the store API response?

Some. Content from store API have correct tags and color:
![Screenshot from 2023-06-20 15-48-46](https://github.com/shopware/frontends/assets/38095299/c6cac1a1-9dab-4dc9-812a-6ef0f5ee15d9)

But its corrupted somewhere, I think, in renderHtml function and rendered like this:
![Screenshot from 2023-06-20 15-47-43](https://github.com/shopware/frontends/assets/38095299/3caff56c-dcc4-4e5c-b4e5-2380ae91c1ee)

Other elements, like ul, ol, table, h tags should have some default styling in FE part I think. And CmsElementText have scoped style which is doing exactly so (partly at least, for h tags and lists). But sadly its not working with scoped tag :thinking:

**Comment by BrocksiNet** [comment]
To be honest ... I totally do not like that Frontends needs to convert this to HTML.
I also want to get rid of this [entities](https://www.npmjs.com/package/entities) dependency (too big client side js). We need a better way. :thinking:

**Comment by kstala** [comment]
There is a problem with add to cart buttons 

https://github.com/shopware/frontends/assets/30267600/5c5fb8bd-1cb3-4608-b139-1998cfa1fe52

**Comment by patzick** [comment]
also with sign in, not hovered
![image](https://github.com/shopware/frontends/assets/13100280/cdd903d3-920e-4bdc-a9cf-6bd3c6bde607)
hovered:
![image](https://github.com/shopware/frontends/assets/13100280/a1b9aaf8-84e8-4fd1-8fe2-2d619dacc691)
