### ISSUE TITLE
not existing params required to be passed in the invoke action payload

### ISSUE THREAD

**Issue by mkucmus** [shopware/frontends#294]
### Description

Some of actions for `invoke` method don't have any payload required to be sent within a request.

![image](https://github.com/shopware/frontends/assets/5596960/d7367419-2180-4849-90b8-a62faced3828)

### Use Case

to not pass unnecessary parameters if not needed

**Comment by BrocksiNet** [comment]
Is this already fixed @patzick?

**Comment by patzick** [comment]
@bojanrajh it's not a bug, it's an enhancement and has low priority for now. We just added it here to not forget :)

**Comment by bojanrajh** [comment]
@BrocksiNet This is probably meant for you. :)

**Comment by patzick** [comment]
yeah sorry! GH autocompletion seems to misunderstood my intention 😅
