### ISSUE TITLE
[Bug] false resolving of home route 

### ISSUE THREAD

**Issue by niklaswolf** [shopware/frontends#32]
The resolving of the home route like it is done right now is not really safe.
https://github.com/shopware/frontends/blob/acd70e94cd252f05fb8c0f2032bac66b090d1934/packages/composables/src/useNavigationSearch.ts#L16
I see that there is a TODO-comment, but it doesn't really explain what the problem is.

For example we have multiple root-categories, one for the "normal" category tree, one for the footer-navigation and so on.
In our case, we do not get the correct root-category (as configured in the saleschannel) as the home category, but the footer category.

**Comment by mkucmus** [comment]
Hey @niklaswolf ! thanks for studying the code 💪🏻 
You are right, the problem occures when there are more than one root category in the repository. 
It's been changed to something more bullet-proof:
currently, for `/` path resolving, which means normally a "homepage", we use `sessionContext.value?.salesChannel?.navigationCategoryId` from the context. which is a wrapper category for main navigation:

https://github.com/shopware/frontends/commit/bf5549885516541e237c60ce1a2fda00080e1aff#diff-4cf41b529fdbc9ede59652256198b99eb400c04017588aaca4c912ce2bf3b7fbR23

Leave your feedback please, if it will work for you 🙏🏻

**Comment by niklaswolf** [comment]
@mkucmus yes, that's exactly what was needed. With this change, the configuration from the saleschannel is respected. Thanks! :) 
I'll therefore close this issue.
