### ISSUE TITLE
[BUG] Mobile version fixes

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After recent changes, the mobile version doesn't look good (especially the login section and product sliders)

https://github.com/shopware/frontends/assets/30267600/48490299-9cd4-403e-9dbc-da0b43d62df3

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by BrocksiNet** [comment]
The problem with the slider is only when you resize the window.

It looks like this for me after a fresh reload:

![Image](https://github.com/shopware/frontends/assets/3763023/1fd57f16-ce71-4d53-a463-13892d50e480)
