### ISSUE TITLE
[BUG] countryId is returning salesChannel.countryId, but that does not update when patching the sessionContext

### ISSUE THREAD

**Issue by SuddenDev** [shopware/frontends#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So I'm trying to build a location switcher and found an issue which I don't really understand: The `countryId` that you can get with the `useSessionContext()` composable comes apparently from the salesChannel. When updating the countryId of sessionContext with the api-client package by invoking the `/store-api/context` PATCH request manually and refreshing the context, the shippingLocation country updates and stays even after refreshing. The salesChannelCountry stays the same.

```typescript
//frontends/packages/composables/src/useSessionContext.ts:205

  const countryId = computed(
    () => sessionContext.value?.salesChannel?.countryId,
  );
```  

### Expected Behavior

I'd expect the countryId to be updated correctly in the sessionContext. Either by correctly referencing `countrId` in the shippingLocation, or by changing the PATCH Method to update the Sales Channel. (Although that does not sound like that's supposed to happen)

**Comment by mdanilowicz** [comment]
Confirmed as a platform bug, the core team is working on it

**Comment by BrocksiNet** [comment]
For reference: NEXT-29989
