### ISSUE TITLE
[BUG] vite-vue-plugin-disable-inputs regex bug

### ISSUE THREAD

**Issue by StanislovasRamanauskas** [shopware/frontends#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In new vite-vue-plugin-disable-inputs package, VueDisableInputsBeforeMount function have regex to find select elements (packages/vite-vue-plugin-disable-inputs/src/index.ts line: 46-47):
``` ts
const foundSelectElements =
          component.match(/<(select|input|button)(.*\s?)([\s\S]*?)?\>/gm) || [];
```
Its meant to select specific elements (select|input|button) opening tag:
![Screenshot from 2023-07-18 14-23-33](https://github.com/shopware/frontends/assets/38095299/7effd1d6-7cad-4ce6-99c5-022bf2dd5078)

But in our case, we have v-if condition in button with > symbol (v-if="current > 0") and regex mistakes that > with tag close symbol:
![Screenshot from 2023-07-18 14-27-23](https://github.com/shopware/frontends/assets/38095299/1efdcf0b-40d2-4fc7-ad2b-cef6f8608c05)

Because of that, :disabled attribute is left outside of foundSelectElements and is not found with hasDisabled (line 50 in same index.ts) function. Therefore second disabled attribute is added, resulting duplicate attribute error in nuxt build.

For now, we fixed this issue in our side, but this bug can cause unexpected errors in app.

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by BrocksiNet** [comment]
How you fixed it? Improved RegEx? :)

**Comment by StanislovasRamanauskas** [comment]
Nah, didn't wanted to edit package code. Just changed condition in our side to have < instead of > :sweat_smile:

**Comment by BrocksiNet** [comment]
The plugin is now deprecated.

See also this https://github.com/shopware/frontends/commit/599f04ce80472b127e11a1e27173b7cafba5842a commit.

If there are some questions pls reopen the issue.
