### ISSUE TITLE
Docs search is not working yet

### ISSUE THREAD

**Issue by mrsunshine** [shopware/frontends#35]
At the moment the search on https://shopware-frontends-docs.vercel.app/ is not working yet. 

If you search you get no results for any search word. Seems docs are not indexed yet or so.

**Comment by mdanilowicz** [comment]
I added a local search. In the future, we are going to use the Algolia engine

#106

**Comment by patzick** [comment]
This is closed, for now, the search is working (not Algolia though) and will be improved in future :)
