### ISSUE TITLE
[BUG] Impossible to override SwXXX components (?)

### ISSUE THREAD

**Issue by bounoable** [shopware/frontends#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The [documentation](https://frontends.shopware.com/getting-started/cms/overwriting-cms.html) states that we should be able to override the `packages/cms-base/components/SwProductCard.vue` component but this doesn't actually work.

It seems like we can only override the components in `packages/cms-base/components/public/cms`, is that correct?

So to override the ProductCard layout, we would need to override `packages/cms-base/components/public/cms/element/CmsElementProductBox.vue` as a 1:1 copy of the original `CmsElementProductBox.vue` but referencing a custom implementation of `ProductCard.vue` ?

Thank you for your help

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by BrocksiNet** [comment]
For me, it looks like you are right. At the moment you need to overwrite the CMS Components that you want to change and use your "customized" SwProductCard inside this. If you only change CmsElmentProductBox this will only help for this one CMS Element. But SwProductCard is used in 4 Files inside public/cms.

@patzick I guess we already talked about making this a way easier? 
Maybe we should push this topic. What do you think?

**Comment by patzick** [comment]
This needs to be corrected in the documentation. Component `SwProductCart` is only the internal component of cms-base package. The `public api` of the package are all `CmsXXX` named components, as this is what is coming from Shopware API as well.

Overwriting that way gives you way more flexibility and no problem with future upgrades of the package itself. So just create `Product Cart` component you wish to have in CMS and use it in desired CMS Element Component

**Comment by BrocksiNet** [comment]
What to do here? 😀
