### ISSUE TITLE
[DOCS] How to use Frontends with two (or more) SalesChannels?

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#359]
### Description

We need to document how a setup with Composable Frontends and two different SalesChannels can look like.

This documentation should also explain or have an example code for a basic store switcher.

Please also consider a way to only have one Frontend with multiple SalesChannels.
Or write down if our suggestion would be to have Frontend for every SalesChannel and the reasons for that.

Also, give some hints about the language Switcher topic (e.g. setup: 2 SalesChannel and everyone with 2 Languages).

### Use Case

Different products in different SalesChannels.

### Additional Context

[Discussion](https://shopwarecommunity.slack.com/archives/C050L6NCMGQ/p1691568842158229) in Slack Channel.

**Comment by maximilian-schwarz** [comment]
Very Interesting. Currently need the same use case.

**Comment by jfrank325** [comment]
Yes, working on this as well.

**Comment by BrocksiNet** [comment]
I created an internal Task (#NEXT-31405) to have some new Endpoint to give us all the needed Information to create a SalesChannel Switch. I will come back to this topic when the new Endpoint is there.

**Comment by BrocksiNet** [comment]
This may also be helpful for different peps:
https://github.com/patzick/frontends-multiinstances-example

**Comment by BrocksiNet** [comment]
@patzick I guess we can close this Issue?
