### ISSUE TITLE
nuxt generate freezes 

### ISSUE THREAD

**Issue by billiaug** [shopware/frontends#36]
When running `nuxt generate` or `npm run generate`, nuxt starts building static pages.
But after about 10min the builder freezes without errors and just hangs.

Testing on a staging Shopware with about 7000 sku's.

**Comment by patzick** [comment]
hey @billiaug!
Our demo page has around 130 products and it generates 2min on M1. 
Looking at the generation time 
![image](https://user-images.githubusercontent.com/13100280/210056878-f3c3b4fb-a61f-48f9-95c0-75648f751701.png)
let's assume 500ms for single page, this would be minumum 83min of generation for your site.
This is definitely something that's worth trying to post at Nuxt repo (https://github.com/nuxt/framework/issues) as a bigger case for SSG and maybe they can improve logs for that kind of generation.

On the other hand having >1h build time might not work for you probably, so I'd recommend to research more into SSR area with cache.

I moved a Q&A thread regarding SSR and SSG to our Discussions, here you can find more about our recommendations: https://github.com/shopware/frontends/discussions/37


Let me know your thoughts

**Comment by billiaug** [comment]
@patzick 

I had similar performance on a an i7 quad core with 32gb ram.
We could definitely have a look at multithreaded rendering.
The SSR duration is not a big issue if we can manage to get delta renders instead of a full build.

After a few attempts I've managed to render all SKU's + content pages.
I would aim for more sku's during testing.
On average our production Shopware's have between 4000 and 50 000 SKU's.
This is a common issue with Shopware 6 core. Development and testing of the core is done with a low number of products and give issues in production.

From an infrastructure and performance viewpoint, SSG has my preference in the SaaS + apps context.
