### ISSUE TITLE
[BUG] getWishlistProducts() throws console error

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Reported via Slack by Stanislovas Ramanauskas:

Hey, noticed that `getWishlistProducts()` function call in `app.vue` throws error in console when user is logged in and does not have any wishlist created yet. Shouldn't it be handled in composable?

![Screenshot from 2023-09-05 18-56-13](https://github.com/shopware/frontends/assets/3763023/b0c7f14e-0b5c-4a49-a45e-7a1b8c34100e)

![Screenshot from 2023-09-05 18-57-34](https://github.com/shopware/frontends/assets/3763023/93c0df7a-e365-492a-a76d-1b257500ae04)

### Expected Behavior

There should not be an error thrown when the wishlist is empty.

### Steps To Reproduce

1. Create a new user (https://frontends-demo.vercel.app/register)
2. Log out, after the user was created
3. Go to this page https://frontends-demo.vercel.app/wishlist
4. Open the dev tools and console
5. Login with your new created user that does not have any wishlist item
6. See the error in the console

### Environment

```markdown
This can be reproduced in our cloud demo.
```

**Comment by mdanilowicz** [comment]
We are not able to hide the 404 network error. This error is logged by the browser. But we are able to fix uncaught in promise.  Fixed in #390
