### ISSUE TITLE
[BUG] Nuxt Warning: Two component files resolving to the same name

### ISSUE THREAD

**Issue by benjamin-ott** [shopware/frontends#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, 

I recently updated nuxt to the newest version (3.7.3) and now there are a lot of warnings because of the cms components i have overwritten.

![Bildschirm­foto 2023-09-19 um 09 05 41](https://github.com/shopware/frontends/assets/8365682/f61d1582-2567-4f70-8927-93462f6c1090)

It seems there were similar problems with this module:
https://github.com/nuxt/content/issues/2266

Thank you for your help.

### Expected Behavior

No warnings for overwritten cms components.

### Environment

```markdown
- OS:
- Node: 18
- pnpm:
```

**Comment by BrocksiNet** [comment]
In **templates/vue-demo-store/nuxt.config.ts** you can set a **priority**:
```
  // components: true,
  components: {
    dirs: [
      {
        path: '~/components',
        priority: 5,
      },
    ],
    global: true,
  },
```

Related [PR](https://github.com/nuxt/nuxt/pull/23156/files) from Nuxt.

When your project has a higher priority the warning goes away. :magic_wand:

**Comment by benjamin-ott** [comment]
@BrocksiNet Thank you!
Works great.
Priority 2 was enough to make the warnings go away.
