### ISSUE TITLE
[FEATURE] adyen payments implementation

### ISSUE THREAD

**Issue by mkucmus** [shopware/frontends#406]
### Description

Implementation of how Adyen payments can be used within Composable Frontends. Including corresponding page in docs.

acceptance criteria:
1. payment intent is being created via gateway (cloud app)
2. frontend components are displayed in the checkout step (credit card, and maybe some others available in not only async flow)
3. docs are extended

### Use Case

It's a showcase how Adyen payments can be integrated in a presentation layer like vue-demo-store. Moreover, it's a good benchmark of existing app (not a plugin) in terms of headless approach.

**Comment by BrocksiNet** [comment]
https://github.com/shopware/frontends/pull/407
