### ISSUE TITLE
[Feature] Composable for breadcrumbs

### ISSUE THREAD

**Issue by benjamin-ott** [shopware/frontends#41]
Hi,

there is already a layout file for the breadcrumb, but the composable (useBreadcrumbs) doesn't seem to exist yet.
Is it possible that you add this in the future?

https://github.com/shopware/frontends/blob/main/templates/vue-demo-store/components/layout/LayoutBreadcrumbs.vue#L2

Thanks, 
Ben

**Comment by elkmod** [comment]
Hey @benjamin-ott - it's currently being worked on - the intended API looks like this:

```ts
export type UseBreadcrumbsReturn = {
  setBreadcrumbs: (breadcrumbs: Breadcrumb[]) => void;
  clearBreadcrumbs: () => void;
  breadcrumbs: ComputedRef<Breadcrumb[] | []>;
};
```

**Comment by patzick** [comment]
added with https://github.com/shopware/frontends/commit/313e0810014611a0429b76b51747536630f24627 :) closing
