### ISSUE TITLE
[BUG] CMS block visibility issues if we disable visibility for devices

### ISSUE THREAD

**Issue by lukvai** [shopware/frontends#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Wrong classes are being rendered in front end cms blocks if visibility is hidden on devices. And return type is wrong 
now 
` const { cssClasses, layoutStyles } = getCmsLayoutConfiguration(
      props.content,
    );
    `
    cssClasses variable has `string | null` return type, but when visibility is set it returns object

### Expected Behavior

If I disable visibility for block on mobile 
![image](https://github.com/shopware/frontends/assets/37104879/831d51cc-b04e-488b-b86a-838f802eb5c0)
It would be visible only for mobile devices

Same goes for other devices
if disabled on tablet it would be disabled only for tabled devices for example from md to lg endpoints

### Steps To Reproduce

1.Create a cms block that wil be rendered on home page
2. disable visibility for mobile
![image](https://github.com/shopware/frontends/assets/37104879/c633439d-af16-4ec6-8396-b758c8ffc25c)
3 It add md:hidden class in 
`packages/helpers/src/cms/getCmsLayoutConfiguration.ts` `getVisibilityClasses` function
4. the block becomes visible only for mobile devices

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by StanislovasRamanauskas** [comment]
Want to add, that if any class from visibilityCssClasses is added in template, and is not used in any other template directly, it will have no effect, because unoCss will not generate it.

**Comment by lukvai** [comment]
To add one more thing while testing found out that when switching visibility and adding a class
![image](https://github.com/shopware/frontends/assets/37104879/c0537dc8-9ef6-492d-855e-2266d8969560)
It renders class like this 0 1 2 3.... basically then it renders keys of object
![image](https://github.com/shopware/frontends/assets/37104879/ff9bf577-d4c1-4c30-86ad-590ddca54b44)

the console.log(cssClasses) in CmsGenericBlock.vue
![image](https://github.com/shopware/frontends/assets/37104879/54b0fc9d-cec3-4afe-a23f-449b78215cfb)

**Comment by mkucmus** [comment]
> Want to add, that if any class from visibilityCssClasses is added in template, and is not used in any other template directly, it will have no effect, because unoCss will not generate it.

that's a good hint. unocss looks up for the occurrences of known css classes in order to attach corresponding css definitions, so from what I see now is to add all known names of hidden-related classes in some comments (can be as a comment, not used in the DOM).
