### ISSUE TITLE
check whether CMS blocks/elements implement settings from Shopping Experiences

### ISSUE THREAD

**Issue by mkucmus** [shopware/frontends#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The thing is to ensure whether all blocks and elements implement properly settings coming from API.

For example:
If there is an attribute of Image set on the backend (in CMS), check if it's properly displayed in the generated HTML, and so on, for other cases and attribues (or block settings like background any many others).

All encountered issues should be reported separately 

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by kstala** [comment]
Text: 
- Text :heavy_check_mark:
- Text banner :heavy_check_mark:
- Teaser text :heavy_check_mark:
- Two columns, teaser text :heavy_check_mark:
- Two columns, text :heavy_check_mark:
- Three columns , text :heavy_check_mark:

Images:
- Image, boxed :heavy_check_mark:
- Image, full-sized :heavy_check_mark:
- Two columns, boxed :heavy_check_mark:
- Three columns, full sized :heavy_check_mark:
- Four columns, boxed :heavy_check_mark:
- Three columns, rounded :heavy_check_mark:
- Three columns, boxed background :heavy_check_mark:
- Image grid :heavy_check_mark:
- Image slider :heavy_check_mark:
- Image gallery :heavy_check_mark:
- Large images gallery 

Videos:
- YouTube video :heavy_check_mark:
- Vimeo :heavy_check_mark:

Text & images:
- Two columns, boxed image & text :heavy_check_mark:
- Two columns, full-sized image & text :heavy_check_mark:
- Three columns, boxed images & text :heavy_check_mark:
- Three columns, captioned images :heavy_check_mark:
- Three columns, image/text cards :heavy_check_mark:
- Three columns, captioned & rounded :heavy_check_mark:
- Hero image :heavy_check_mark:


Commerce:
- Product name & manufacturer logo :heavy_check_mark:
- Three columns, product boxes :heavy_check_mark:
- Product slider :heavy_check_mark:
- Image gallery and buy box :heavy_check_mark:
- Product description & reviews :heavy_check_mark:
- Cross Selling :heavy_check_mark:

Sidebar: 
- Category navigation :heavy_check_mark:

Form:
- Form :heavy_check_mark:
- Custom form :heavy_check_mark:

3D:
- 3D Object

**Comment by BrocksiNet** [comment]
I also found in CE the new HTML Element:
![image](https://github.com/user-attachments/assets/f07a3964-da77-40c0-9dd9-86574912a7db)

**Comment by BrocksiNet** [comment]
@kstala can we close that task? 

I think the research is done, and we have new tasks to implement the missing CMS elements, right?

**Comment by BrocksiNet** [comment]
Related issues: #1528, #1305, #1306
