### ISSUE TITLE
[BUG] Landing pages, 500er error after hard reload

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Landing pages do not work after a hard reload, only when you use them through the main navigation (client site rendering). :warning: 

### Expected Behavior

- The landing page works when you open it via a direct link
- The landing page works when you open it via navigation

### Steps To Reproduce

- You go to https://frontends-demo.vercel.app/
- Navigate to "Summer BBQ" then click on "Summer Giveaway"
- You should see the page, everything looks fine
- Now do a hard reload or open the page direct (https://frontends-demo.vercel.app/Summer-BBQ/Summer-Giveaway/)
- You will see the 500er error page

**Comment by patzick** [comment]
Should it be closed by #453 ?

**Comment by mdanilowicz** [comment]
No, this task is blocked by the backend task (31557)

**Comment by joostaasman** [comment]
@mdanilowicz  Do you have any update on this?

**Comment by BrocksiNet** [comment]
I pushed the topic to the core team again.
We can also provide a fix for that.
Unfortunately, has not been solved.
Do you have a workaround @joostaasman?

**Comment by joostaasman** [comment]
@BrocksiNet Thanks for pushing this topic to the team. For now, we're using direct links.

**Comment by mkucmus** [comment]
the problem does not longer exist
