### ISSUE TITLE
[BUG] Wrong link resolving for LP pages

### ISSUE THREAD

**Issue by mdanilowicz** [shopware/frontends#447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Navigation menu links are built wrongly for some specific cases.

![Screenshot 2023-11-01 at 10 16 57](https://github.com/shopware/frontends/assets/7597086/5acf6f8d-6bda-4a94-a3eb-6dd0ba0b7cec)

![Screenshot 2023-11-01 at 10 15 01](https://github.com/shopware/frontends/assets/7597086/f8fab3da-b4f9-4c9e-ae18-232324bf07e4)

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by BrocksiNet** [comment]
@mdanilowicz is that related with #446?

**Comment by mdanilowicz** [comment]
Yes, it would be related to this task
