### ISSUE TITLE
Wrong typing of getSeoUrls in api-client

### ISSUE THREAD

**Issue by niklaswolf** [shopware/frontends#46]
The type [here](https://github.com/shopware/frontends/blob/13e31103502434a92bc533bd0e78fe5541557004/packages/api-client/src/services/pageService.ts#L55) is wrong, it should be the following type

`Promise<EntityResult<"seo_url", { apiAlias: string; seoPathInfo: string }[]>>`

I'll provide a PR later.

**Comment by patzick** [comment]
👌 thank you! Closing as resolved!
