### ISSUE TITLE
[BUG] Shopware types are not exported in new API client

### ISSUE THREAD

**Issue by z0n** [shopware/frontends#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The README for the new API client includes this example to import the Shopware types:
```ts
import type {
  operationPaths,
  operations,
  components,
} from "@shopware/api-client/api-types";
```
When trying this with the latest version of @shopware/api-client (0.5.0), the module `@shopware/api-client/api-types` can't be found.

### Expected Behavior

It should be possible to import the Shopware types like described in the example.

### Environment

```markdown
- OS: macOS 14.1.1
- Node: 21.2.0
- yarn: 1.22.21
```

**Comment by patzick** [comment]
hey @z0n 
Looks like yarn cached something, I checked with our stackblitz example and it works: https://stackblitz.com/edit/github-jpbvrb?file=src%2FadminApiClient.ts

![image](https://github.com/shopware/frontends/assets/13100280/1513daea-f4d9-4141-bf0e-31ca200b63dd)


please recheck and if the problem still occurs prepare some reproduction on Stackblitz

**Comment by z0n** [comment]
Hi @patzick, thanks for looking into it. I found the error on my side: The `moduleResolution` was set to `bundler` instead of `node` in our tsconfig.json. Now it works!
