### ISSUE TITLE
[FEATURE] Maintenance mode

### ISSUE THREAD

**Issue by StanislovasRamanauskas** [shopware/frontends#469]
### Description

Now that maintenance mode is supported via store api (since Shopware version 6.5.7.0), it would be nice to have an example of how best to handle it in Frontends apps. Maybe to add different layout if its maintenance mode?

Also, not sure how maintenance mode should work with these lines uncommented:
https://github.com/shopware/frontends/blob/main/templates/vue-demo-store/app.vue#L24
Because then error response code is always 500

### Use Case

Maintenance mode in Frontends app

**Comment by patzick** [comment]
In case of API error messages (503, when maintenance mode is on), you're redirected to the error page. So you can display anything you want there. I'd read the status code and display a specific error page for maintenance mode.

For our demo template, the page on maintenance mode turned on looks like this:

![image](https://github.com/shopware/frontends/assets/13100280/fd96fa75-126b-4867-a84a-efcf8eb0de3a)


Not sure what would be a requirement for this issue :)

**Comment by StanislovasRamanauskas** [comment]
> In case of API error messages (503, when maintenance mode is on), you're redirected to the error page. So you can display anything you want there. I'd read the status code and display a specific error page for maintenance mode.
> 
> For our demo template, the page on maintenance mode turned on looks like this:
> 
> ![image](https://private-user-images.githubusercontent.com/13100280/286599684-fd96fa75-126b-4867-a84a-efcf8eb0de3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjM4NzQsIm5iZiI6MTcwMTI2MzU3NCwicGF0aCI6Ii8xMzEwMDI4MC8yODY1OTk2ODQtZmQ5NmZhNzUtMTI2Yi00ODY3LWE4NGEtZWZjZjhlYjBkZTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEzMTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZDFkNjEwZWNkMjk4NDk4YjVjNWJmMjk4ZDFlMGM3YjAwMjU3OWI5YjQxYWY1MDBlZDJiOGI1NDhjNzM2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bcNQTVVJoBGPEjQVdZ0O_lOdP-TilIIeCRDztFX48-Q)
> 
> Not sure what would be a requirement for this issue :)

@patzick yep, exactly did that in my case - read the status code and displayed maintenance template if its 503. So if we don't need example in demo store, we can close this.

the only thing that can be improved here is that error page is not displayed if ssr is disabled (like we talked in Slack)
