### ISSUE TITLE
[BUG] #452 broke import statements

### ISSUE THREAD

**Issue by eyecatchup** [shopware/frontends#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Update:** In fact, the merge of #452 seems to have broken import statements all over the place; e.g.:

<img width="618" alt="Bildschirmfoto 2023-11-27 um 22 40 56" src="https://github.com/shopware/frontends/assets/845131/4b225518-1c63-44c4-9b6b-e069264acfc7">

--

**Initial report:** After the latest commit, running / building the templates fails due to broken import statements. See my comment here https://github.com/shopware/frontends/commit/e2c225f1d69a5d523f3c1e6c90449ee28f98b2f2#commitcomment-133623757

### Expected Behavior

Templates use valid module import specifiers

### Steps To Reproduce

Click the "Open in StackBlitz" button here https://github.com/shopware/frontends/tree/e2c225f/templates/vue-demo-store#try-it-online and watch the terminal

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by patzick** [comment]
Thank you for this issue @eyecatchup!
We expect now to break a few things, and we count on the community to help us improve that. The full scope of the recent changes you might find here: https://github.com/shopware/frontends/discussions/471

This issue should resolved by #474
