### ISSUE TITLE
Vitest not working with vue-demo-store template and custom composables

### ISSUE THREAD

**Issue by benjamin-ott** [shopware/frontends#50]
Hi,

I have a project based on the vue-demo-store template. 
My goal is to use Vitest to test my own composables (which import internally the composables from @shopware-pwa/composables-next).

I got the following Error when i run my tests:

<img width="1257" alt="Bildschirmfoto 2023-01-30 um 09 02 23" src="https://user-images.githubusercontent.com/8365682/215420677-812a8037-f3ac-4ecb-b437-601566d5949b.png">

I resolved this with a custom alias in my vitest.config.ts:

`resolve: {
      alias: {
          '~': path.resolve(__dirname, '.'),
          '@shopware-pwa/composables-next': '@shopware-pwa/composables-next/dist/index.mjs'
      }
  },`

But i think this shouldn't have to be necessary right?

**Comment by patzick** [comment]
hey @benjamin-ott 
Auto-import works when you will register module, as Vitest might not be aware of that, so in this case, adding the alias in config is a proper solution to configure that :) 
A section in docs might probably be added explaining how to set it up. Would that be helpful?

**Comment by benjamin-ott** [comment]
Hi @patzick, thank you for your answer.
I guess it's fine for me working with the alias!
But as you pointed out, others really might benefit from a section in the documentation, because it might not be obvious for everybody how to solve the error.

**Comment by benjamin-ott** [comment]
Hi @patzick,
it is now working without the alias for @shopware-pwa/composables-next with the current version.
In my opinion this issue could be closed. Thank you.

**Comment by patzick** [comment]
Great to hear! Thank you, @benjamin-ott, for your feedback! Closing
