### ISSUE TITLE
[Feature] ApiClient and Composable for Documents (Invoices, Delivery Note, Credit Note)

### ISSUE THREAD

**Issue by meeshoogendoorn** [shopware/frontends#51]
I couldn't find a composable or endpoint in api-client for downloading documents from Shopware 6, such as invoices or delivery notes. Should this be integrated into a separate composable, or would it be better to implement it in the existing [useOrderDetails composable](https://github.com/shopware/frontends/blob/main/packages/composables/src/useOrderDetails.ts) since it can only be used when order details are available? 

Use Case:
 * Customers can download invoice from their account when logged in
 * Customers can download proof of payment when picking up order from store
 * Customers can download Delivery note with all info about their delivery

Click here for the [Stoplight docs of downloading document using store-api](https://shopware.stoplight.io/docs/store-api/22f78d63ebd4c-download-generated-document)

**Comment by patzick** [comment]
It's more UI related, as it's just a link probably the best would be to invoke api-client for that.
We'll look into this case and provide missing methods! :)

**Comment by BrocksiNet** [comment]
This is done already. See this commit https://github.com/shopware/frontends/commit/240eae89daf685dff1b76914d263ee08f9e44b41

Tell me if something missing or not working like expected.
