### ISSUE TITLE
[BUG]  Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by bastianhilton** [shopware/frontends#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following the documentation on Shopware Frontends, it says to add `@shopware-pwa/cms-base` to the `extends: [ ]` section of `nuxt.config.ts`, however whenever I do that and start up my nuxt project I get the following error message.

```
 ERROR  Cannot read properties of undefined (reading 'options')

 ERROR  Cannot read properties of undefined (reading 'options')
```

Once I remove the extends my nuxt project is able to startup properly. 

### Expected Behavior

Following the documention here https://frontends.shopware.com/framework/shopping-experiences.html#install-the-package it doesn't mention to do that, however the templates have it in the extend section and not in the module section. What is the correct way of adding this module to the nuxt.config.ts file?

### Steps To Reproduce

Create Nuxt Project
install @shopware-pwa/cms-base module
Add it to the extends: ["@shopware-pwa/cms-base"] section of your nuxt.config.ts(.js) file
Start up the project 

### Environment

```markdown
- OS: Windows 11
- Node: 21.1.0
- pnpm: N/A
```

### Anything else?

N/A

**Comment by mkucmus** [comment]
CMS Base package as a layer is available only in `canary` version currently. Once the maturity of the setup is enough, the documentation will be updated for this option as well. 
You mentioned the [docs](https://frontends.shopware.com/framework/shopping-experiences.html), and there is no work about using layers yet, so if you are using the `latest` or a specific stable version, please don't use layers. We are working on that 🙌🏼
