### ISSUE TITLE
[FEATURE] Cross-selling Endpoint and api client method

### ISSUE THREAD

**Issue by jonathan-martz** [shopware/frontends#519]
### Description

I m currently working on a headless demo shop and noticed that there is a endpoint missing for fetch the cross selling products.

### Use Case

Fetch Cross Selling Products by product id

### Proposed Solution

Adding the Endpoint with a method to fetch the data by product id.

**Comment by patzick** [comment]
hey @jonathan-martz 
this can be achieved by `loadAssociations` inside `useProductAssociations` but you're right - current API client doesn't have this defined
