### ISSUE TITLE
SwFilterPrice.vue: Ambiguous indirect export: _debounce 

### ISSUE THREAD

**Issue by niklaswolf** [shopware/frontends#52]
Error message from browser console:
```
The requested module '/_nuxt/node_modules/.vite/deps/@shopware-pwa_helpers-next.js?v=153e22da' does not provide an export named '_debounce' (at SwFilterPrice.vue:3:1)
```

This breaks client side navigation completely when trying to get to a page that uses this component indirectly (e.g. category pages)

**Comment by patzick** [comment]
@niklaswolf this should be already fixed with https://github.com/shopware/frontends/commit/ece79b021c25499ac9ac4d54b707f27f9e25eb68. I forgot to mention it here after the release. Please confirm all works well now :)

**Comment by patzick** [comment]
closing, let us know if you experience problems with this after version upgrade
