### ISSUE TITLE
[FEATURE] Possibility to easy overwrite the internal SwProductCard Component

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#537]
### Description

Currently, you have to overwrite the component that is using the SwProductCard and then place your own ProductCard there. Find a nice way to overwrite the SwProductCard once (in Project/demo-store) and it is updated in all public components that are using it.

### Use Case

Better DX, easier overwrite for one of the most used components.

**Comment by patzick** [comment]
this topic came back a couple of times now :) TLDR: overriding is done by changing the CMS components only by purpose. Every element should be considered separately as is coming from the Shopping Experience API. To unify this there should be a change there and unified CmsElementProduct

Making any internal component like `SwProductCard` public would create additional API. Any change done by us would cause problems for users and unconscious breaking changes with upgrades.
