### ISSUE TITLE
Manufacturer and Properties are null with useProduct() 

### ISSUE THREAD

**Issue by KalleJoP** [shopware/frontends#55]
Hey, 
how can I get the manufacturer and the properties of an product? 
When I use `useProduct()` these fields are null. 
![Bildschirm­foto 2023-02-10 um 16 33 13](https://user-images.githubusercontent.com/61844416/218131145-9314b873-741e-403f-a330-343705d50117.png)
![Bildschirm­foto 2023-02-10 um 16 33 31](https://user-images.githubusercontent.com/61844416/218131223-d843fd6e-0f13-4d93-8f95-84f2dc7bb7dc.png)

Is it just not possible at the time or am I just to dumb?

Thanks for help 😄

**Comment by StanislovasRamanauskas** [comment]
@KalleJoP Faced similar issue. Manufacturer name is in product listing product object but not in wishlist page product object from useWishlist composable.  Haven't checked why yet, but answer to your question will help me too :D

**Comment by BrocksiNet** [comment]
Where you want to use it? 

And did you already checked the `useProductAssociations` composable?

**Comment by StanislovasRamanauskas** [comment]
Any news on this topic?

**Comment by BrocksiNet** [comment]
Hello @StanislovasRamanauskas :wave: ,

we have already solved the problem internally. And in general you just need to pass other associations to the `await getProduct(productId, associations, apiInstance)`. Even then you have to adjust the types for typescript. We haven't merged the solution yet, as there will be a new store-api client as a base, which is more flexible and supports most of the store-api parameters. Always keep in mind that you can [override composables](https://shopware-frontends-docs.vercel.app/getting-started/overwriting-composables.html) or [create your own composables](https://vuejs.org/guide/reusability/composables.html#async-state-example) to fetch data from any request as you need it. But yes, we will also fix this in the demo store when the new store api client is ready.

Thanks for your feedback :grin:

**Comment by mdanilowicz** [comment]
I'm closing this issue. Feel free to add a comment or create a new issue if there are any questions  :)
