### ISSUE TITLE
[FEATURE] api-next: Use application/json as default accept header

### ISSUE THREAD

**Issue by shyim** [shopware/frontends#554]
### Description

Right now the client uses https://jsonapi.org/ and this is a hassle for any developer who wants to do something in a fast way with the API

### Use Case

Simpler api responses, which makes more sense than JSON API

### Proposed Solution

Provide a switch to plain JSON using `accept: application/json` header,

**Comment by patzick** [comment]
@shyim, can you elaborate on what you are trying to achieve? Would be nice to have a reproduction of:
- what you do
- what you get
- what you expect to get

as we do operate on JSON responses
![image](https://github.com/shopware/frontends/assets/13100280/6a8d2965-3569-4734-b6bd-aae80dd0ca40)

you can play around with example app here: https://stackblitz.com/github/shopware/frontends/tree/main/examples/new-api-client

**Comment by shyim** [comment]
Example code:

```

console.log(await adminApiClient.invoke(
    "searchSeoUrl post /search/seo-url"))
```

<img width="663" alt="image" src="https://github.com/shopware/frontends/assets/6224096/3e024c4b-b83e-4817-957a-0054c3c72452">

<img width="509" alt="image" src="https://github.com/shopware/frontends/assets/6224096/b065ebd8-42ce-41ba-8503-715961d29562">


You see in the output the links to different pages and so one. As shopware uses [JSON API](https://jsonapi.org/) when no accept header given, or explicitly set to that. Every developer hates this response format, therefore we should use `application/json` only.

**Comment by patzick** [comment]
okay right, I was watching `token` endpoint, others did not have this header. Fix is on the way! Thanks for clarification 🙌
