### ISSUE TITLE
[FEATURE] Link back to product from Mini-Cart and Cart-Page

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#559]
### Description

Currently, we do not have any link from the line item in the mini-cart or cart page back to the product page.

### Use Case

Improve the usability for the user.

### Proposed Solution

With the `referencedId` we already know the corresponding `productId` but we do not know the nice speaking URL for that product. So how do we solve this without additional requests? Is this possible? I could imagine that we use the `payload` of the line item during the add item to the cart action/event.

### Alternatives Considered

Consider moving the function into a reusable composable.

### Additional Context

The solution needed for the demo-store template.

**Comment by khanSoliheen** [comment]
@patzick, can I get more insights on this. I have attached the ss below. Please lemme know if this is correct
<img width="1419" alt="Screenshot 2024-04-21 at 18 09 02" src="https://github.com/shopware/frontends/assets/43225019/61c9c453-1383-42ab-81ef-c70b0df4970e">

**Comment by patzick** [comment]
hey @khanSoliheen!
This is more about making products inside a mini cart to be linked back to the product page. In your screenshot example - clicking on the title `LAVENDA Product Variants` should redirect to that specific product page :)

**Comment by khanSoliheen** [comment]
@patzick , please confirm, it should navigate to http://localhost:3000/detail/bbf36734504741c79a3bbe3795b91564 when we click on LAVENDA Product Variants title. Am I right? Thanks.

**Comment by khanSoliheen** [comment]
@patzick , It is done. You can find the PR [https://github.com/shopware/frontends/pull/977](here)
