### ISSUE TITLE
Missing "country" value in billing/shipping addresses of useOrderDetails Composable

### ISSUE THREAD

**Issue by LouisEiermann** [shopware/frontends#56]
The `useOrderDetails()` composable does return `NULL` for the value of "country" at the moment.

This is a problem for example when we want to display the country of a Billing/Shippingaddress in the useraccount.

The issue is due to the country association missing in the API call to shopware.

```
const orderAssociations = {
  associations: {
    lineItems: {
      associations: {
        cover: {}
      }
    },
    addresses: {},
    deliveries: {
      associations: {
        shippingMethod: {}
      }
    },
    transactions: {
      associations: {
        paymentMethod: {}
      },
      sort: "-createdAt"
    }
  }
};
```

Inside here, we need to add the respective association to also get the value for "country".  :)

**Comment by niklaswolf** [comment]
I think it would be very nice to be able to provide additional associations to the composable as a parameter. These should then be merged with the default ones.

There will always be people that need different/additional data and right now there is no possibility with this (and other) composables

**Comment by patzick** [comment]
Thanks for the input; this is something we're currently working on!
First, we want to improve the overall API client and provide a better "composition" for the sets of fields, so it's defined on the build time by the specific project, as everyone has different needs.
You can already do this by [overwriting composable](https://shopware-frontends-docs.vercel.app/getting-started/overwriting-composables.html) to your specific needs, but we want to make the DX better in this area.

**Comment by LouisEiermann** [comment]
That sounds good!
But in this case, "country" should definitely be included in the API call for the addresses per default :)

**Comment by mdanilowicz** [comment]
I added the `association` parameter to the `useOrderDetails` to support projects that will still use api package
