### ISSUE TITLE
[FEATURE] api-client: Listen when a new token has been created

### ISSUE THREAD

**Issue by shyim** [shopware/frontends#562]
### Description

There is no event, to listen when the api client fetches a new token based on the refresh token. That would be kinda nice, so I can persist it in the database and use it for further calls in the sessionData

### Use Case

Get notified that we have a new accessToken and store them in the database.

**Comment by patzick** [comment]
@shyim you have method `onAuthChange` which does exactly that, this way you can persist session data

example from readme using Cookies, but you can use database instead:
```
export const adminApiClient = createAdminAPIClient<operations, operationPaths>({
  baseURL: "https://demo-frontends.shopware.store/api",
  sessionData: JSON.parse(Cookies.get("sw-admin-session-data") || "{}"),
  onAuthChange(sessionData) {
    Cookies.set("sw-admin-session-data", JSON.stringify(sessionData), {
      expires: 1, // days
      path: "/",
      sameSite: "lax",
    });
  },
});
```

it also is automatically stored in apiClient as well so no need to use `setData` - if the session expired then before the next invocation apiClient automatically invoked `refresh_token` and uses new `accessToken`.


Please share some use case if that workflow is not working for you, we'll help :)

**Comment by shyim** [comment]
Whoops didnt saw that
