### ISSUE TITLE
Possibility to override storefrontUrl in useUser register

### ISSUE THREAD

**Issue by niklaswolf** [shopware/frontends#57]
Right now it is not possible to provide a custom value for `storefrontUrl` through the params, because it always gets set after destructuring the params.
https://github.com/shopware/frontends/blob/1fa56aa3c97b45f664a5f273c97e489e366523ce/packages/composables/src/useUser.ts#L167

I think it would be more user friendly to switch `storefrontUrl` and the destructuring, so that you can override it through params if you want.

**Comment by GM-Alex** [comment]
The main problem is `getStorefrontUrl` is using `apiInstance.config.endpoint` which makes absolutely no sense, see https://github.com/shopware/frontends/blob/e51c37a4e5c4cd6756068ad06d6501efdf7095f5/packages/composables/src/useInternationalization.ts#L23 . Your suggestion is just a workaround for a, I guess, ridiculous workaround which breaks the whole process, if the storefront has a different url than the backend. Also the comment `apiIntanceUrl - should be removed after resolving backend multi domains problems` identify this. @patzick @mdanilowicz when will this be reverted?

**Comment by BrocksiNet** [comment]
I guess your discussion is also connected to this  https://github.com/shopware/frontends/issues/54. If not pls correct me.

Just wanna tell you that we have this topic on our list and will also discuss with the core team about `getStorefrontUrl` vs `apiInstance.config.endpoint` and how domain handling should work for headless salesChannels. Our goal is to simplify this and do not have this confusion. After having a solution we will update docs related to this topic.

**Comment by niklaswolf** [comment]
That's ok, but we need a possibility to override this in the meantime. Right now it's in some cases as described above not possible to use the composable

**Comment by niklaswolf** [comment]
That's possible indeed, you're right. I did not think this through when writing my last comment ;)

**Comment by mdanilowicz** [comment]
Thank you for your feedback. We are aware that managing `storeforntUrl` in this form is not the best solution. We are working on changing the whole flow related to internalisation so you can expect changes in this area. When? We are not able to specify the exact date now. But this topic has the most significant priority now.

The simplest solution, for now, is to override composable and add a new config field that will represent your `storeforntUrl`.

You can also have the same URL for the headless, api and backed and redirect each routing to the dedicated app. This will require a special routing app/configuration.
