### ISSUE TITLE
[FEATURE] check also .env defined variables in order to validate shopware credentials

### ISSUE THREAD

**Issue by mkucmus** [shopware/frontends#573]
### Description

change condition to check also corresponding setting in .env file
https://github.com/shopware/frontends/blob/e2c225f1d69a5d523f3c1e6c90449ee28f98b2f2/packages/nuxt3-module/plugin.ts#L15

```text
NUXT_PUBLIC_SHOPWARE_SHOPWARE_ENDPOINT="http://localhost:8000"
NUXT_PUBLIC_SHOPWARE_SHOPWARE_ACCESS_TOKEN="SWSCBHFSNTVMAWNZDNFKSHLAYW"
```

### Use Case

the error is being thrown even if corresponding settings are set in .env file and it can be used correctly

### Proposed Solution

don't throw an error if .env* file has the corresponding config for api-client.

**Comment by mdanilowicz** [comment]
I checked the issue, and everything looks ok.
There are two requirements from Nuxt for it to work.

.env must be in the scope. If it were placed in the main folder of the repo, envs would not be merged.
Init values must be declared in the Nuxt config file. 

```
...
    public: {
      shopware: {
        shopwareEndpoint: "",
        shopwareAccessToken: "",
        devStorefrontUrl: "",
      },
    },
...
```
