### ISSUE TITLE
Navigation between cms pages takes too long on slower connections

### ISSUE THREAD

**Issue by benjamin-ott** [shopware/frontends#59]
Hi,

i tested the navigation between cms pages on: https://frontends-demo.vercel.app/ with a "slow 3g" connection enabled to simulate a slower connection.

The navigation from the home page to another category takes about 4 to 5 seconds. 
That's very long and for the user it looks a long time like nothing is happening.

The reason for this are the 2 requests i think:

![Bildschirmfoto 2023-03-07 um 10 11 45](https://user-images.githubusercontent.com/8365682/223377076-dbe9ff5e-65f8-436c-8f5b-7905e0ffe05a.png)

First "/store-api/seo-url" is called and after that "store-api/category" is called.

We did some tests with the page controller of the old [SwagShopwarePwa](https://github.com/shopware/SwagShopwarePwa) plugin and had much better results (half the time).

Is something like the page controller planned for the shopware core? 
I think this would really benefit the user experience. At the moment the page change is just too slow.

**Comment by sschwarz-allbuyone** [comment]
Hi, 

In your Screenshot is Network Throtteling active and set to "Slow 3G" ;-)

I tested the same Url with deactivated Throtteling with this result:
 
![image](https://user-images.githubusercontent.com/10849709/223383043-69745ee8-f4c8-4d50-8352-d3eafa235acf.png)

**Comment by benjamin-ott** [comment]
@sschwarz-allbuyone yes should have mentioned that in the original post, sorry 😃 

But what about slower connections? If there a 2 requests needed it takes double the time...

**Comment by BrocksiNet** [comment]
Hello :wink: 

I can confirm that we need to improve the loading time for **slow 3g connections**. So thanks for pointing that out @benjamin-ott :+1: 

The demo store is just a showcase and we will also improve the demo over time. We still have some issues that we need to discuss with the core team as well, to make less requests to get the same results and also to improve the overall performance of the store api.

In any case, there are already ways to improve this without waiting for improvements on the admin/store api side (also the update to 6.5 RC will improve this).

I'll just mention two ways here:
- Write a custom Nuxt endpoint that solves this under the hood (better connection + cachable, how to do this (?) ... we will create a documentation for it, will take some time).
- Adding a proxy in Nuxt to avoid preflights and speed up the whole requests (this is in work).

By the way we also have a new template for [astro](https://github.com/shopware/frontends/tree/main/templates/astro). This allows you to pre-generate a lot of stuff and only add dynamic islands where needed ... could also be an option if your visitors are mostly on slow 3g connections.

:wave:  Björn

**Comment by BrocksiNet** [comment]
Some updates.

Look at this PR to solve the seoURL problem:
https://github.com/shopware/frontends/pull/194

Look at this blog post to know how to use nuxt middelware with cache (optional):
https://www.brocksi.net/blog/frontend-api-with-nuxt-and-nitro-will-lead-to-flexibility/

---

@benjamin-ott The partial "loading" topic I have on my backlog list. 
Can we close this issue or you see something left?

**Comment by benjamin-ott** [comment]
@BrocksiNet i already saw the blog post, looks very interesting, thank you! We will definitely try this in our project.

The seo url stuff looks interesting too, but we solved this in a different way for us. We use just one new custom route which can handle seo and technical urls and responds with the corresponding cms page. 

In my opinion you could close this issues for now.
