### ISSUE TITLE
[BUG][API] Links from  RTE are not translated as a valid links

### ISSUE THREAD

**Issue by mdanilowicz** [shopware/frontends#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

TBA

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by BrocksiNet** [comment]
Could you link the core issue here? Is that task blocked now?

**Comment by BrocksiNet** [comment]
**Solution for that can be found here**
https://github.com/shopware/shopware/commit/3dfe23d832f0459e0903004550620baf384e893f
