### ISSUE TITLE
Overwrite ProductCard on all cms based pages

### ISSUE THREAD

**Issue by Sananes** [shopware/frontends#67]
Hi guys and girls,

Currently any ProductCard used within cms pages, product listing pages defaults to the shopware-pwa SwProductCard.vue component. However, the one in `components/product/ProductCard.vue` is only used within product page, I'm assuming? My question is, how do I make a global ProductCard.vue component that overwrites all instances of it instead of on a per page use case.

Thanks in advance!

**Comment by BrocksiNet** [comment]
Solutions and Informations from Slack Discussion, reposted here to help others.

Quote from Stanislovas Ramanauskas:
> I had similar case, where I needed to use my own product card in category page, so I overrided CmsElementProductListing component in
> `templates/vue-demo-store/components/cms/` directory and used my card there.

Quote from Patryk:
> Nuxt is resolving names by folder structure, so if you have
> `/components/public/some/name.vue`
> then component name is PublicSomeName
> you can repeat folder structure in name like
> `/components/cms/Name.vue`
> `/components/cms/CmsName.vue`
> are the same component resolving as CmsName

Quote from Patryk:
> Additionally - list of all elements with Card:
> CmsElementCrossSelling
> CmsElementProductBox
> CmsElementProductListing
> CmsElementProductSlider

**Comment by Sananes** [comment]
@BrocksiNet thanks for referencing the discussions in slack! I will now close this issue! Thanks for all the help!
