### ISSUE TITLE
Got: [plugin:vite:import-analysis] Failed to resolve import "@shopware-pwa/api-client" from "app.vue"

### ISSUE THREAD

**Issue by Lanzelot711** [shopware/frontends#681]
I am coming from React and I am new to vue and nuxt and I am trying to figure out whether shopware frontends is a good fit for our projects.

I initialized a new blank project and tried to do the following as a simple test: 

<script setup lang="ts">
const { refreshSessionContext } = useSessionContext();

onMounted(() => {
  refreshSessionContext();
});

import { getProducts } from "@shopware-pwa/api-client";

const result = await getProducts()
console.log(result)

</script>

<template>
  <div id="app">
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
<style>
@import "./style.css";
</style>

Got: [plugin:vite:import-analysis] Failed to resolve import "@shopware-pwa/api-client" from "app.vue". Does the file exist?

I also tried it within a page, but did not work either.

I find @shopware-pwa/api-client in the package.json and I ran npm i, but it did not help.

Am I missing something?

The example on Stackblitz does not work either:

https://frontends.shopware.com/packages/api-client/getProducts.html

**Comment by Lanzelot711** [comment]
okay a manual npm install fixed it, but now I am getting corse header problems. How is it that they don't happen when running the demo store?

the credentials are still the demo shopware ones

**Comment by Lanzelot711** [comment]
So now I am running a local dockware install of shopware and I configured localhost:3000 as the domain. Still I get the coarse header problems when trying to register a new user in the demo. The rest of the content is loading. 

![image](https://github.com/shopware/frontends/assets/154733307/ef234e88-fb84-448e-80f3-3c3e44d121b0)

**Comment by BrocksiNet** [comment]
Do you still have problems? Or got it working?

**Comment by BrocksiNet** [comment]
Please reopen if you have further problems or questions. Thx.
