### ISSUE TITLE
[FEATURE] check Shopware 6 v6.6-rc compatibility

### ISSUE THREAD

**Issue by mkucmus** [shopware/frontends#686]
### Description

check whether our stack is compatible with the upcoming major release:

- create an instance
- connect frontends-demo-next to the newly created instance
- run e2e tests
- create compatibility tasks if there are differences

### Use Case

getting aligned with upcoming major version of API.

```[tasklist]
### related issues
- [ ] https://github.com/shopware/frontends/issues/781
```

**Comment by kstala** [comment]
Checked areas:
- [ ] Products (PDP, add to cart, product prices, digital product) 
- [ ] Login / Registration 
- [ ] Category / listing (filters, pagination)
- [ ] Checkout (as log in customer, as a guest)
- [ ] Search

**Comment by kstala** [comment]
I ran e2e tests on our instance with 6.6 and ... 
![image](https://github.com/shopware/frontends/assets/30267600/12b90eba-fe87-4c25-b33c-6c20c494e931)
... I need to check the product review and product variant

**Comment by BrocksiNet** [comment]
I guess this is done via https://github.com/shopware/frontends/pull/805. If not please reopen.
