### ISSUE TITLE
[BUG] API Client does not use context language/currency

### ISSUE THREAD

**Issue by kennyzehn** [shopware/frontends#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I changed the currency and language. But the API returns data always in the shop default language|currency. I figured out that this happens since version 0.3.0.

`
await apiClient.invoke(
      "updateContext patch /context",
      {
        languageId: lang,
        currencyId: currency,
      }
    );
`

### Expected Behavior

Return data in context language and currency

### Steps To Reproduce

1. Change language and currency via `updateContext patch /context`
2. Fetch Products or Navigation Items
3. Check result :) 

### Environment

```markdown
- OS: MacOS
- Node: v18.17.0
- pnpm: /
```

**Comment by patzick** [comment]
Confirmed this is working in the newest canary (soon stable release), to be sure I added integration tests checking these scenarios: https://github.com/shopware/frontends/pull/1055/files#diff-dbb71a145ade0a70115cdf95381458a5a3d4c3cebfdab921012ac5315d3c4ac5
