### ISSUE TITLE
[BUG] Broken Product Listing Pagination on Category Page

### ISSUE THREAD

**Issue by fabianeichinger** [shopware/frontends#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- When changing page, the number of requested elements per page jumps from 15 to 100
- The next button always jumps to the last page

### Expected Behavior

- All pages should contain an equal number of elements (except the last if there are not enough remaining)
- Next button should navigate to next page

### Steps To Reproduce

1. https://frontends-demo.vercel.app/Cooking-pleasure-Provence/Eat/
2. Click on page 2 in the pagination controls
-> You'll see "No products found 😔" (URL ends with `?p=2`)
3. Use browser back button
-> URL ends without the search param, but you'll still see the error placeholder
4. Refresh page (without search param so to start on page 1)
5. Click the next [>] button
-> Again "No products found 😔", but notice that the URL ends with `?p=3`.

### Environment

```markdown
Demo linked in repository README, same bugs in an in-development project
```

### Anything else?

For the failing next button, `SWPagination` seems to emit last instead of the next page number.

For the jump in items per page, it seems like the request for `/store-api/category/…` includes a smaller number of items than the subsequent request to `/store-api/product-listing/…`.

**Comment by BrocksiNet** [comment]
I know that issue and currently working on that. Thx for reporting anyway.

**Comment by gutschik** [comment]
@BrocksiNet We're facing the same issue. Could you please share any updates or an estimated timeline for when this issue might be addressed? I'm asking merely for planning purposes on my end, and I completely understand if it's challenging to provide a specific timeframe.

**Comment by BrocksiNet** [comment]
You can check out this [Draft](https://github.com/shopware/frontends/pull/642) currently. Or check the [Preview](https://frontends-demo-git-feat-filter-count-8b03c7-shopware-frontends.vercel.app/Products/) here.

**Comment by fabianeichinger** [comment]
@BrocksiNet Thanks for the quick reply. The preview looks much improved. Hope to see this merged soon!

**Comment by BrocksiNet** [comment]
Closed by https://github.com/shopware/frontends/pull/642
