### ISSUE TITLE
[BUG] bfcache Issue

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**That's the problem**
![image](https://github.com/shopware/frontends/assets/3763023/7650918d-8a12-4c7d-86e3-ef1e54c16529)

**That could be a solution**
https://github.com/nuxt/nuxt/pull/23667

### Expected Behavior

The Issue is not shown anymore in Lighthouse for the demo-store.
The demo-store works like before without any errors.

### Anything else?

Another related https://github.com/shopware/frontends/issues/539

**Comment by InstantlyMoist** [comment]
Currently having the same issue, no dependencies seem to interfere with it.

**Comment by BrocksiNet** [comment]
I was researching a lot today about that issue. :mag: 

I assume that the issue comes from [nuxt i18n module](https://v8.i18n.nuxtjs.org/getting-started/setup).

So I created a empty nuxt/vite project with that command:
`pnpm dlx nuxi@latest init <project-name>`

Testing this in **preview mode** is important because Vite is opening a WebSocket in dev mode, which can also cause an issue with bfcache.

So the steps for **testing** are:
1. pnpm build
2. pnpm preview
3. Open the Page in a Chrome Browser
4. Open Dev Tools -> Application -> Back/Forward Cache -> Click on Test Button

**Result:**
- Blank Nuxt/Vite Project -> No bfcache Issue :heavy_check_mark: 
- Blank Nuxt/Vite Project + i18n module -> bfcache Issue :x: 

Somehow I assume it has something to do with `detectBrowserLanguage` function. But not sure about that. :confused:

**Comment by BrocksiNet** [comment]
Today, I tested again with the `Blank Nuxt/Vite Project + i18n module` and can not reproduce the `bfcache` Issue anymore. This is great 🎉 

So, it would be super cool to eliminate that problem in the **demo-store** template. 💡 

Currently, we are using `@nuxtjs/i18n` in version `8.3.1`, and I guess we need to update package.json to `^8.5.5`.

But when I execute this command:
`pnpm run generate && pnpm run preview`

I got a lot of warnings and errors. So, we need to fix the generate command first.

**Comment by BrocksiNet** [comment]
So when  I update @nuxtjs/i18n and comment out this part in app.vue:
`//useBroadcastChannelSync();`

We do not have any `bfcache` Issue anymore:
![Image](https://github.com/user-attachments/assets/2d6064e9-9b5a-466a-b69f-51aa50983bec)

FYI @mdanilowicz
