### ISSUE TITLE
[BUG] errors during adding a product to cart aren't displayed

### ISSUE THREAD

**Issue by mkucmus** [shopware/frontends#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add a product to cart with some impossible quantity I'm able to add only one of it, but the message from the response is not displayed
![image](https://github.com/shopware/frontends/assets/5596960/3956b369-0620-45a6-a9a5-2d588ba8edb8)

### Expected Behavior

the errors from the response are displayed, so I know what happened and why I don't have exact number of items in my cart

### Steps To Reproduce

1. go to `/detail/3c40bbdab5a94212b7834f879ab34539` route
2. add 9999 quantity
3. see the only one product was added
4. I can see errors object with proper warning attached - in `line-item` endpoint response

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by mdanilowicz** [comment]
Will be covered by https://github.com/shopware/frontends/pull/1215
