### ISSUE TITLE
[BUG] AddToCart and Clearance sale activated

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I have a product with that **stock configuration**:
![image](https://github.com/shopware/frontends/assets/3763023/b3615c74-4bd0-43ea-bd4e-220bf6539404)

I can still click the **AddToCart** Button in Frontend and get a success message.

However, the product is not added to the cart ... everything looks correct as a customer.

### Expected Behavior

As a customer, I would expect a message that the product is not in stock and the AddToCart Button should be disabled.

I would also expect another error message when I am allowed (not deactivated) to click the AddToCart Button.

Suggestion: Compare the template with the default storefront and how the flow is there.

### Steps To Reproduce

**Test-Product:**
http://localhost:3000/LAVENDA-Product-Variants/SW20004.1

**Comment by mkucmus** [comment]
it duplicates those issues: 

https://github.com/shopware/frontends/issues/464
https://github.com/shopware/frontends/issues/782
