### ISSUE TITLE
[FEATURE] Add pagination for wishlist page

### ISSUE THREAD

**Issue by khanSoliheen** [shopware/frontends#894]
### Description

Description
pagination to change the current page if results are more than 10

Use Case
I wanna add the pagination buttons on the bottom of the wishlist page - when I'm logged-in

### Use Case

It divides large sets of data or content into separate pages, allowing users to navigate through them sequentially. It is commonly implemented in scenarios where loading and displaying all data at once would be inefficient or impractical due to performance concerns or usability

**Comment by khanSoliheen** [comment]
@mkucmus, It is done and raised a pull request. Please assign this enhancement to me.

**Comment by BrocksiNet** [comment]
PR can be found [here](https://github.com/shopware/frontends/pull/893/files).
