### ISSUE TITLE
[BUG] Fehlende slotId im Contact Form

### ISSUE THREAD

**Issue by innpyt** [shopware/frontends#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ContactFormRoute.php erwartet `slotId`, sonst wird es an `core.basicInformation.email` gesendet.
Und `slotId` ist irgendwie nicht im `/store-api/pwa/page` response drin, sowie `cms_slot_id`, der im Definition auch drin steht.
Id ist laut CmsSlotDefinition ist nicht apiAware.

PS: mit eigene extension habe ich es auch nicht gekriegt.
`class SlotExtension extends EntityExtension
{
    public function extendFields(FieldCollection $collection): void
    {
        $collection->add((new IdField('id', 'id'))->addFlags(new Runtime(), new PrimaryKey(), new Required(), new ApiAware()));
    }

    public function getDefinitionClass(): string
    {
        return CmsSlotDefinition::class;
    }
}`
gibt ein 500 mit Undefined array key \"cms_slot.id\", und ohne Requires/Primary flags kriege ich einfach "id": null.

### Expected Behavior

slotId oder cms_slot_id steht im pwa/page response drin

### Steps To Reproduce

- /store-api/pwa/page mit folgende body aufrufen
{
    "path": "Service/Kontakt",
    "associations": {} 
},

Erwartet:

### Environment

```markdown
- OS: Ubuntu 20.12.2
- Node: 20.12.2
- pnpm:0.0.1
- SW: 6.5.3.3
```

**Comment by BrocksiNet** [comment]
@mdanilowicz [this](https://github.com/shopware/shopware/blob/v6.6.4.0/changelog/release-6-6-4-0/2024-05-29-slotid-apiaware.md) is released and can now be fixed :tada:

**Comment by BrocksiNet** [comment]
We are closing this issue. If it is relevant to PWA, you could open an issue [there](https://github.com/vuestorefront/shopware-pwa). Thanks.
