### ISSUE TITLE
[ACCESSIBILITY] Homepage - Headings should not be empty

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#900]
### Description

Ensures headings have discernible text

### Use Case

<img width="1467" alt="image" src="https://github.com/shopware/frontends/assets/30267600/e12d2f4c-e68f-499c-b8cf-a2cd80724520">

**Comment by BrocksiNet** [comment]
I fixed the h1 and h3 via the Admin. But currently, it is still cached on live ... locally this error is already gone. I checked that.

**Comment by BrocksiNet** [comment]
This is now fixed.
