### ISSUE TITLE
[BUG]  setCurrentFilters-method of useListing-composable not working

### ISSUE THREAD

**Issue by SampoVirmasalo** [shopware/frontends#907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Problem
Currently when using the setCurrentFilters method of useListing composable with any filter, the search does not inject the filter into the API request body properly.

For example when calling the method as follows, a request to the client is made but filters are not applied properly:

**Example**
```ts
// const {filterResults} = useListing({ /* omitted */ });

function filterResults(filter) {
  // ... transformers, custom stuff...etc.
  serCurrentFilters({
    code: 'manufacturer',
    value: '018d35f5b5757076adea38044bb96937' // 👈 manufacturer ID from my Shopware
  });
  // ... maybe more stuff
}
```

**Request body to the Shopware API**
```JSON
{
  "limit":10,
  "search":"",
  "p":"1",
  "navigationId":"018db20234207be8948e3a4b46501435",
  "manufacturer":"",
  "price": {"min":0,"max":0},
  "rating": null,
  "shipping-free":false,
  "properties":"",
  "code":"manufacturer",
  "value":"018d35f5b5757076adea38044bb96937"
}
```

## Cause
I've tracked this problem to the code of setCurrentFilters-method:
```ts
const setCurrentFilters = (filter: { code: string; value: any }) => {
    const appliedFilters: RequestParameters<"searchPage"> = Object.assign(
      {},
      getCurrentFilters.value,
      filter, // 🚨 Here's the problem
      {
        query: getCurrentFilters.value?.search,
        manufacturer: getCurrentFilters.value?.manufacturer?.join("|"),
        properties: getCurrentFilters.value?.properties?.join("|"),
      },
    );
    if (_storeAppliedListing.value) {
      _storeAppliedListing.value.currentFilters = {
        ...appliedFilters,
        manufacturer: appliedFilters.manufacturer?.split("|"),
        properties: appliedFilters.properties?.split("|"),
      };
    }
    return search(appliedFilters);
  };
```
This method does not apply the filters as Shopware API reads them, as it simply adds "code" and "value" property into the `const appliedFilters` object. 

What it should do, is to either overwrite default properties of the `const appliedFilters`.

### Expected Behavior

setCurrentFilters should apply the key and value to appliedFilters -object in a way that Shopware API wants them. 

Consider calling setCurrentFilters like this:
```ts
function filterResults(filter) {
  serCurrentFilters({
    code: 'manufacturer',
    value: '018d35f5b5757076adea38044bb96937' // 👈 manufacturer ID from my Shopware
  });
}
```

The request should be like this:
```JSON
{
  "limit":10,
  "search":"",
  "p":"1",
  "navigationId":"018db20234207be8948e3a4b46501435",
  "manufacturer":"018d35f5b5757076adea38044bb96937",  // 👈 where the filter value should go
  "price": {"min":0,"max":0},
  "rating": null,
  "shipping-free":false,
  "properties":"",
}
```

Not like this:

```JSON
{
  "limit":10,
  "search":"",
  "p":"1",
  "navigationId":"018db20234207be8948e3a4b46501435",
  "manufacturer":"",
  "price": {"min":0,"max":0},
  "rating": null,
  "shipping-free":false,
  "properties":"",
  "code":"manufacturer",  // 👈 Not like this
  "value":"018d35f5b5757076adea38044bb96937" // 👈 Not like this
}
```

### Steps To Reproduce

1. Set up Nuxt project with the Shopware Nuxt modules
2. Create listing using `useListing()` -composable
3. Create event that calls `setCurrentFilters()` -method with argument like this for example:
```ts
setCurrentFilters({
  code: 'manufacturer',
  value: 'any-manufacturer-id`
})
```

Shopware version: 6.5.7.3 
Shopware-composables version: 0.0.0-canary-20240426081217 (see: [Github, composables, useListing]( https://github.com/shopware/frontends/blob/main/packages/composables/src/useListing.ts#L479))

### Environment

```markdown
- OS: MacOS Sonoma, 14.4.1 (23E224)
- Node: v18.18.0
- yarn: v1.22.19
```

**Comment by BrocksiNet** [comment]
Thank you for creating this issue and proposing a solution. This is related to https://github.com/shopware/frontends/issues/841, and you can also have a look [here](https://github.com/shopware/frontends/blob/main/templates/vue-demo-store/pages/search.vue#L27) (how it is currently solved in search page). 

But yes, we know we need more :heart: for the useListing Composable and unify it with search.

**Comment by BrocksiNet** [comment]
@SampoVirmasalo created a PR #1338 

Can you validate and test it from your site? Thx.
