### ISSUE TITLE
[BUG] status and state property return no values 

### ISSUE THREAD

**Issue by FlemingNick** [shopware/frontends#923]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Both the "status" property of the useOrderDetails composable and the "state" property of useOrderPayment return "undefined", even though the values are set. We use the shopware frontend demo project as a foundation, where the Bug seems to occur aswell.

Addition: shippingAddress is also affected

(as discussed in https://app.slack.com/client/T011TTK0DMK/activity)

### Expected Behavior

The state, status and shippingAddress of the order are logged correctly

### Steps To Reproduce

`const {
        loadOrderDetails,
        shippingAddress,
        billingAddress,
        shippingMethod,
        order,
        subtotal,
        total,
        shippingCosts,
        status
    } = useOrderDetails(orderId);

    const { paymentUrl, handlePayment, isAsynchronous, state, paymentMethod } = useOrderPayment(order);

    onMounted(async () => {
        const SUCCESS_PAYMENT_URL = `${window?.location?.origin}/checkout/success/${orderId}/paid`;
        const FAILURE_PAYMENT_URL = `${window?.location?.origin}/checkout/success/${orderId}/unpaid`;

        await loadOrderDetails();

        // console.log('shipping', shippingAddress, 'billing', billingAddress);
        console.log(status, state);

        handlePayment(SUCCESS_PAYMENT_URL, FAILURE_PAYMENT_URL);
    });`
    
    Putting the console.log in a .then() function after the loadorderDetails also did not work.

### Environment

```markdown
- OS: Ubuntu 20.04 auf Windows 10
- Node: 20.10.0
- pnpm: 8.15.3
- vue: 3.4.21
- nuxt: 10.9.0
- "@shopware-pwa/cms-base": "canary",
- "@shopware-pwa/composables-next": "canary",
- "@shopware-pwa/helpers-next": "canary"
- "@shopware-pwa/nuxt3-module": "canary",
- "@shopware-pwa/types": "canary",
- "@shopware/api-client": "canary",
```

**Comment by mdanilowicz** [comment]
fixed in #933
