### ISSUE TITLE
Fix lint-staged workflow

### ISSUE THREAD

**Issue by patzick** [shopware/frontends#93]
Related to #85 

We use lint-staged, but checking out the repository is not create a git hook which runs this command.

### Acceptance criteria
1. after checkout and init repository, git gook for lint-staged is set

### Additional note (nice to have)
1. Lint command is also running prettier over linted files, so there is no local difference to see

**Comment by patzick** [comment]
@BrocksiNet  we already have prettier in eslint config, look here:
https://github.com/shopware/frontends/blob/c253d92f1730a1a5f78b6855176250dd8044d180/packages/eslint-config-shopware/index.js#L3

the question is why ist's not working the same way as prettier would 🤔

**Comment by BrocksiNet** [comment]
Fixed in https://github.com/shopware/frontends/pull/129

**Comment by patzick** [comment]
@BrocksiNet, it's not fixed, in #129 we improved demo template with config, but the workflow is still missing hooks, so modified code is not yet automatically linted and formatted before the commit

**Comment by BrocksiNet** [comment]
Sure, then let's talk about the how? 

You want to add husky again? Or another way without commit hooks?

**Comment by patzick** [comment]
Don't think we have other options now, husky seems to be a good option for now to avoid further linting problems
