### ISSUE TITLE
[BUG]  `slotId` of a slot on a CMS page

### ISSUE THREAD

**Issue by mdanilowicz** [shopware/frontends#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://shopwarecommunity.slack.com/archives/C050L6NCMGQ/p1716548194192029?thread_ts=1715774256.076039&cid=C050L6NCMGQ

https://shopwarecommunity.slack.com/archives/C050L6NCMGQ/p1716546934635989

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by patzick** [comment]
@mdanilowicz, please add the Acceptance Criteria for that task so it's clear what exactly needs to be done here. It is also nice to have the reproduction steps for testing the solution

**Comment by mdanilowicz** [comment]
Fixed in the backend https://github.com/shopware/shopware/blob/trunk/src/Core/Content/Cms/Aggregate/CmsSlot/CmsSlotDefinition.php#L59
