### ISSUE TITLE
[BUG] ProductDetailPage: CrossSelling and ProductSlider have no SeoUrls

### ISSUE THREAD

**Issue by cfreak** [shopware/frontends#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CrossSelling and ProductSlider have no SeoUrls

https://frontend.luftkuss.ch/Bundle-Test-happy-Mothersday-Ballon-Set/B2092

seoUrl Informations are missing on:

`relatedProducts.value = computed(() => props.content?.data?.products ?? []).value;`

### Expected Behavior

CrossSelling and ProductSlider should be linked with SeoUrls 

### Environment

```markdown
"@shopware-pwa/cms-base": "^0.0.0-canary-20240529152552",
    "@shopware-pwa/composables-next": "^0.0.0-canary-20240529152552",
    "@shopware-pwa/helpers-next": "^0.0.0-canary-20240529152552",
    "@shopware-pwa/nuxt3-module": "^0.0.0-canary-20240529152552",
    "@shopware-pwa/types": "^0.0.0-canary-20240529152552",
    "@shopware/api-client": "^0.0.0-canary-20240529152552",
```

**Comment by patzick** [comment]
this should be fixed with #871
